services:
  - type: web
    name: leba-app
    runtime: docker
    plan: free

    dockerfilePath: ./Dockerfile
    dockerContext: .

    healthCheckPath: /health

    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

      - key: SUPABASE_URL
        sync: false

      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false

      - key: VITE_SUPABASE_URL
        sync: false

      - key: VITE_SUPABASE_ANON_KEY
        sync: false

      - key: GROQ_API_KEY
        sync: false


      - key: GROQ_MODEL
        value: llama-3.1-8b-instant

      - key: GROQ_AUDIT_MODEL
        value: llama-3.3-70b-versatile
